config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  devise_for :owners

  resources :properties, only: [:index, :new , :show, :create] do
    resources :proposals, only: [:show, :new, :create] do
      post 'accept', on: :member
    end

    get 'add_location_purpose', on: :member
    post 'location_purpose', on: :member

    resources :season_rates, only: [:show, :new, :create]
    resources :unavailable_dates, only: [:show, :new, :create]

    get 'search_by_type', on: :collection
    get 'search_by_location', on: :collection
  end

  get 'properties_by_purpose/:id', to: 'location_purposes#index', as: 'properties_by_purpose'

  get 'my_proposals', to: 'proposals#index', as: 'my_proposals'
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id                 :integer          not null, primary key
#  location           :string
#  area               :string
#  title              :string
#  description        :text
#  daily_rate         :decimal(, )
#  rooms              :integer
#  minimum_rent_days  :integer
#  maximum_rent_days  :integer
#  maximum_occupancy  :integer
#  usage_rules        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  property_type_id   :integer
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#

class Property < ApplicationRecord
  belongs_to :property_type
  has_many :proposals
  has_many :season_rates
  has_many :unavailable_dates
  belongs_to :owner
  has_and_belongs_to_many :location_purposes

  validates :title, presence: true

  validates :location, presence: {
    message: 'Você deve informar a Localização'
  }
  validates :rooms, presence: {
    message: 'Você deve informar o Quantidade de Quartos'
  }
  validates :daily_rate, presence: {
    message: 'Você deve informar o Preço da Diária'
  }

  has_attached_file :photo, styles: { medium: "318x180>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  do_not_validate_attachment_file_type :photo

end

app/models/property_type.rb
# == Schema Information
#
# Table name: property_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PropertyType < ApplicationRecord
  has_many :properties
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_owner!, only: [:index, :new, :create,
                                             :add_location_purpose,
                                             :location_purpose]

  def index
    @properties = current_owner.properties
  end

  def new
    @property = Property.new
    @property_types = PropertyType.all
    @location_purposes = LocationPurpose.all
  end

  def create
    @property = Property.new(property_params)
    @property.owner = current_owner
    if @property.save
      flash[:message] = 'Imóvel cadastrado com sucesso'
      redirect_to property_url @property
    else
      @property_types = PropertyType.all
      @location_purposes = LocationPurpose.all
      render :new
    end
  end

  def show; end

  def search_by_type
    # @properties = Property.joins(:property_type).where(property_types: { name: params[:name] })

    @types = PropertyType.where(name: params[:name])
    @properties = Property.where(property_type: @types)
    if @properties.empty?
      flash[:error] = 'Nenhum imóvel encontrado'
      redirect_to request.referer
    else
      render :results
    end
  end

  def search_by_location
    @properties = Property.where(location: params[:location])
    if @properties.empty?
      flash[:error] = 'Nenhum imóvel encontrado'
      redirect_to request.referer
    else
      render :results
    end
  end

  def add_location_purpose
    @location_purposes = LocationPurpose.all
  end

  def location_purpose
    property = Property.find(params[:id])
    location_purpose = LocationPurpose.find(params[:location_purpose_id])
    property.location_purposes << location_purpose
    property.save
    redirect_to property
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:title, :location, :property_type_id,
                                     :area, :description, :daily_rate, :rooms,
                                     :minimum_rent_days, :maximum_rent_days,
                                     :maximum_occupancy, :usage_rules,
                                     :photo, :location_purpose_ids)
  end
end

app/views/properties/add_location_purpose.html.erb
<%= form_tag location_purpose_property_path, method: :post do %>
  <%= label_tag :location_purpose_id, 'Propósito de locação' %>
  <%= select_tag :location_purpose_id, options_from_collection_for_select(@location_purposes, "id", "title") %>
  <%= submit_tag 'Adicionar' %>
<% end %>

app/views/properties/index.html.erb
<% if owner_signed_in? %>
  <p>Bem-vindo, <%= current_owner.first_name %></p>
<% end %>

<h2>Meus Imóveis</h2>
<div class="row">
  <% if @properties.empty? %>
    <div class="alert alert-danger" role="alert">
      Nenhum imóvel cadastrado
    </div>
  <% else %>
    <% @properties.each do |property| %>
    <div class="col-4">
      <%= render partial: '/shared/property_thumbnail', locals: {property: property}%>
    </div>
    <% end %>
  <% end %>
</div>

app/views/properties/new.html.erb
<h1>Cadastre um Imóvel</h1>
<% if @property.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
    <% @property.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <div class="col-md-6">
    <h4>Cadastrar um imóvel</h4>
    <hr>
    <%= form_for @property, html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :property_type_id, 'Tipo do Imóvel'  %>
        <%= f.collection_select(:property_type_id, @property_types,
                                :id, :name, {},class: 'form-control') %>
      </div>
      <div class="form-group">
        <%= f.label :location , 'Localização'%>
        <%= f.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :area , 'Área'%>
        <%= f.text_field :area, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description , 'Descrição'%>
        <%= f.text_field :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :location_purpose_ids, 'Propósito da locação'  %>
        <%= f.collection_select(:location_purpose_ids, @location_purposes,
                                :id, :title, {},class: 'form-control') %>
      </div>
      <div class="form-group">
        <%= f.label :daily_rate , 'Valor da Diária'%>
        <%= f.text_field :daily_rate, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :rooms , 'Quantidade de Quartos'%>
        <%= f.text_field :rooms, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :minimum_rent_days , 'Mínimo de Diárias'%>
        <%= f.text_field :minimum_rent_days, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :maximum_rent_days , 'Máximo de Diárias'%>
        <%= f.text_field :maximum_rent_days, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :maximum_occupancy , 'Ocupação Máxima'%>
        <%= f.text_field :maximum_occupancy, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :usage_rules , 'Regras de Uso'%>
        <%= f.text_field :usage_rules, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :photo , 'Foto'%>
        <%= f.file_field :photo %>
      </div>

      <%= f.submit 'Cadastrar', class: "btn btn-primary" %>
    <% end %>
  </div
</div>

app/views/properties/results.html.erb
<% @properties.each do |property| %>
  <p><%= property.title %></p>
  <p><%= property.property_type.name %></p>
  <p><%= property.location  %></p>
  <p><%= property.area %></p>
  <p><%= property.description %></p>
  <p><%= number_to_currency(
      property.daily_rate , unit: "R$ ", separator: ",", delimiter: "")%></p>
  <p><%= property.photo %></p>
<% end %>

app/views/properties/show.html.erb
<h1>Imóvel</h1>
<hr>
<dl class="row">
  <dt class="col-sm-3">Título:</dt>
  <dd class="col-sm-9"><%= @property.title %></dd>

  <dt class="col-sm-3">Tipo da propriedade:</dt>
  <dd class="col-sm-9"><%= @property.property_type.name %></dd>

  <dt class="col-sm-3">Localização:</dt>
  <dd class="col-sm-9"><%= @property.location %></dd>

  <dt class="col-sm-3">Area:</dt>
  <dd class="col-sm-9"><%= @property.area %></dd>

  <dt class="col-sm-3">Descrição:</dt>
  <dd class="col-sm-9"><%= @property.description %></dd>

  <dt class="col-sm-3">Propósitos de locação</dt>
  <dd class="col-sm-9">
    <ul>
      <% if @property.location_purposes.any? %>
        <% @property.location_purposes.each do |location_purpose| %>
          <li><%= location_purpose.title %></li>
        <% end %>
      <% else %>
        <li>Nenhum propósito cadastrado</li>
      <% end %>
      <% if owner_signed_in? %>
        <li><%= link_to 'Adicionar propósito de locação', add_location_purpose_property_path(@property) %></li>
      <% end %>
    </ul>
  </dd>

  <dt class="col-sm-3">Valor da diária:</dt>
  <dd class="col-sm-9"><%= number_to_currency(@property.daily_rate) %></dd>

  <dt class="col-sm-3">Quantidade de quartos</dt>
  <dd class="col-sm-9"><%= @property.rooms %></dd>

  <dt class="col-sm-3">Período maximo para locação:</dt>
  <dd class="col-sm-9"><%= @property.minimum_rent_days %>
    dias</dd>

  <dt class="col-sm-3">Período minimo para locação:</dt>
  <dd class="col-sm-9"><%= @property.maximum_rent_days %>
    dias</dd>

  <dt class="col-sm-3">Foto:</dt>
  <dd class="col-sm-9"><%= image_tag @property.photo.url(:medium) %></dd>

  <dt class="col-sm-3">Maximo de convidados</dt>
  <dd class="col-sm-9"><%= @property.maximum_occupancy %></dd>

  <dt class="col-sm-3">Regras de uso:</dt>
  <dd class="col-sm-9"><%= @property.usage_rules %></dd>

  <div class="col-sm-12"></div>
  <br>
  <dt class="col-sm-3">Propostas</dt>
  <dd class="col-sm-9">

    <% @property.proposals.each do |proposal| %>
      <% if proposal.status == 'waiting' %>
        <dl class="row">
          <dt class="col-sm-3">Nome do usuario:</dt>
          <dd class="col-sm-9"><%= proposal.user.name %></dd>

          <dt class="col-sm-3">Email do usuario:</dt>
          <dd class="col-sm-9"><%= proposal.user.email %></dd>

          <dt class="col-sm-3">Valor total da proposta:</dt>
          <dd class="col-sm-9"><%= number_to_currency(proposal.total_amount_calculator) %>
            <dd class="col-sm-9">
              <%= link_to "Aceitar proposta #{proposal.id}", accept_property_proposal_path(@property, proposal), {method: :post, class: 'btn btn-sm btn-success'} %>
              <hr>
            </dl>

          <% end %>
        <% end %>
      </dd>
    </dl>
  </dl>
<div class="row action-buttons">
  <% if user_signed_in? %>
    <div class="col-md-3">
      <%= link_to 'Enviar Proposta', new_property_proposal_path(@property), class: 'btn btn-primary' %>
    </div>
  <% end %>
<% if owner_signed_in? %>
  <div class="col-md-3">
    <%= link_to 'Cadastrar preço de Temporada', new_property_season_rate_path(@property), class: 'btn btn-primary' %>
  </div>
  <div class="col-md-3">
    <%= link_to 'Cadastrar Período Indisponível', new_property_unavailable_date_path(@property), class: 'btn btn-primary' %>
  </div>
<% end %>
</div>