config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  devise_for :owners

  resources :properties, only: [:index, :new , :show, :create] do
    resources :proposals, only: [:show, :new, :create] do
      post 'accept', on: :member
    end

    get 'add_location_purpose', on: :member
    post 'location_purpose', on: :member

    resources :season_rates, only: [:show, :new, :create]
    resources :unavailable_dates, only: [:show, :new, :create]

    get 'search_by_type', on: :collection
    get 'search_by_location', on: :collection
  end

  get 'properties_by_purpose/:id', to: 'location_purposes#index', as: 'properties_by_purpose'

  get 'my_proposals', to: 'proposals#index', as: 'my_proposals'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @property_types = PropertyType.all
    @properties = Property.all
    @location_purposes = LocationPurpose.all
  end
end

app/views/home/index.html.erb
<%= flash[:error] %>
<% if owner_signed_in? %>
  <p>Bem-vindo, <%= current_owner.first_name %></p>
<% end %>

<div class="row">
  <% if @properties.empty? %>
    <div class="alert alert-danger" role="alert">
      Nenhum imóvel cadastrado
    </div>
  <% else %>
    <% @properties.each do |property| %>
    <div class="col-4">
      <%= render partial: '/shared/property_thumbnail', locals: {property: property}%>
    </div>
    <% end %>
  <% end %>
</div>

<% if @location_purposes.any? %>
  <ul>
    <% @location_purposes.each do |location_purpose| %>
      <li><%= link_to location_purpose.title, properties_by_purpose_path(location_purpose) %></li>
    <% end %>
  </ul>
<% end %>