config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  devise_for :owners

  resources :properties, only: [:index, :new , :show, :create] do
    resources :proposals, only: [:show, :new, :create] do
      post 'accept', on: :member
    end

    get 'add_location_purpose', on: :member
    post 'location_purpose', on: :member

    resources :season_rates, only: [:show, :new, :create]
    resources :unavailable_dates, only: [:show, :new, :create]

    get 'search_by_type', on: :collection
    get 'search_by_location', on: :collection
  end

  get 'properties_by_purpose/:id', to: 'location_purposes#index', as: 'properties_by_purpose'

  get 'my_proposals', to: 'proposals#index', as: 'my_proposals'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AluguelTemporada</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= link_to 'Aluga Temporada', root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cadastrar Imóvel', new_property_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Minhas Propostas', my_proposals_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Entrar como locador', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
        <% if !owner_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Entrar como proprietário', new_owner_session_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sair', destroy_owner_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <%= form_tag(search_by_type_properties_path, method: "get", class: 'form-inline') do %>
        <%= label_tag :name, 'Busca por Tipo do Imóvel', class: 'text-light mr-sm-2' %>
        <%= text_field_tag :name, nil, class: 'form-control mr-sm-2' %>
        <%= submit_tag "Buscar por Tipo", class: 'btn btn-outline-secondary mr-sm-2' %>
      <% end %>
    </div>
    <div>
      <%= form_tag(search_by_location_properties_path, method: "get", class: 'form-inline') do %>
        <%= label_tag :location, 'Busca por Localização', class: 'text-light mr-sm-2' %>
        <%= text_field_tag :location, nil, class: 'form-control mr-sm-2' %>
        <%= submit_tag "Buscar por Localização", class: 'btn btn-outline-secondary mr-sm-2' %>
      <% end %>
    </div>
  </nav>
  <div>
    <%= flash[:message] %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>